#!/usr/bin/env perl
# Record
#   * Number of tickets sold for each ticket type
use strict;
use Encode qw(decode_utf8);
use YAPC2013;
use JSON;
use utf8;

my $app = YAPC2013->new;

my $hf_api = $app->container->get('API::HRForecast');

my %event2id = (
    sponsor => 11777,
    sponsor_en => 11779,
);
foreach my $event (keys %event2id) {
    my $id = $event2id{$event};
    my $json = `$^X ./script/fetch_csv $id`;
    my $data = JSON::decode_json($json);
    my $count = 0;
    foreach my $key (keys %$data) {
        $count += $data->{$key}->{ticket_count};
    }
    $hf_api->record("yapcasia2013", "ticket", $event, $count);
}

# we need to be more specific with tickets
my @event_ids = (
    11775,
    11778
);
my %ticket_name2id = (
    "学生チケット（無料）" => "student",
    "先行販売 2日通し券(Tシャツ付き)" => "early_bird"
);
foreach my $event (@event_ids) {
    my $json = `$^X ./script/fetch_csv $event`;
    my $data = JSON::decode_json($json);

    my %tickets;
    foreach my $key (keys %$data) {
        my $entry = $data->{$key};
        my $ticket_type_id = $ticket_name2id{ $entry->{ticket_type} };
        $tickets{ $ticket_type_id } += $entry->{ticket_count};
    }

    foreach my $ticket_type (keys %tickets) {
        my $count = $tickets{$ticket_type};
        $hf_api->record("yapcasia2013", "ticket", $ticket_type, $count);
    }
}