#!/usr/bin/env perl
# Record
#   * Number of tickets sold for each ticket type
use strict;
use Encode qw(decode_utf8);
use YAPCApp;
use JSON;
use utf8;

my $app = YAPCApp->new;

my $hf_api = $app->container->get('API::HRForecast');

my %event2id = (
    sponsor => 38605,
    sponsor_en => 38608,
);
foreach my $event (keys %event2id) {
    my $id = $event2id{$event};
    my $json = `$^X ./script/fetch_csv $id`;
    my $data = JSON::decode_json($json);
    my $count = 0;
    foreach my $key (keys %$data) {
        $count += $data->{$key}->{ticket_count};
    }
    $hf_api->record("yapcasia2014", "ticket", $event, $count);
}

# we need to be more specific with tickets
my @event_ids = (
    38603,
    38607
);
my %ticket_name2id = (
    "Student pass" => "student_en",
    "学生チケット(無料)" => "student",
    "Early Bird 2 day pass" => "early_bird_en",
    "先行販売 2日通し券(Tシャツ付き)" => "early_bird",
    "2 day pass w T-shirt" => "twoday_pass_en",
    "2日通し券 (Tシャツ付き)" => "twoday_pass",
    "8/29 1 day pass w T-shirt" => "oneday_pass_1_en",
    "8/29 1日券 (Tシャツ付き)" => "oneday_pass_1",
    "8/30 1 day pass w T-shirt" => "oneday_pass_2_en",
    "8/30 1日券 (Tシャツ付き)" => "oneday_pass_2",
    "8/29 1 day pass w/o T-shirt" => "oneday_pass_1_no_tshirt_en",
    "8/29 1日券 (Tシャツ無し)" => "oneday_pass_1_no_tshirt",
    "8/30 1 day pass w/o T-shirt" => "oneday_pass_2_no_tshirt_en",
    "8/30 1日券 (Tシャツ無し)" => "oneday_pass_2_no_tshirt",
);
foreach my $event (@event_ids) {
    my $json = `$^X ./script/fetch_csv $event`;
    my $data = JSON::decode_json($json);

    my %tickets;
    foreach my $key (keys %$data) {
        my $entry = $data->{$key};
        my $ticket_type_id = $ticket_name2id{ $entry->{ticket_type} };
        $tickets{ $ticket_type_id } += $entry->{ticket_count};
    }

    foreach my $ticket_type (keys %tickets) {
        my $count = $tickets{$ticket_type};
        $hf_api->record("yapcasia2014", "ticket", $ticket_type, $count);
    }
}
