#!/usr/bin/env perl

use strict;
use Encode qw(decode_utf8);
use YAPCApp;
use JSON;
use File::Temp qw(tempfile);
use File::Copy qw(move);

my $id = 11777;
my $json = `$^X ./script/fetch_csv $id`;
my $data = JSON::decode_json($json);

my @sponsors;
for my $key ( keys( $data ) ){
    my $twitter_id = $data->{$key}->{twitter_id};
    push @sponsors, $twitter_id;
}

my $file = '/var/lib/jpa/yapcasia.org/yapcasia2013-app/var/individual_sponsors.json';
my ($fh, $tempfile) = tempfile;
print $fh JSON::encode_json(\@sponsors);
close $fh;

move $tempfile, $file
  or die "Can't move \"$tempfile\" to \"$file\": $!";
